language: csharp
mono: none
dotnet: 2.1.402
sudo: required

jobs:
  include:
    - stage: restore and build
      script: dotnet restore src/Nethermind
      name: "Restore projects"
    - script: dotnet build src/Nethermind
      name: "Build projects"
    - stage: run tests
    - script: dotnet test src/Nethermind/Nethermind.KeyStore.Test
      name: "Nethermind.KeyStore.Test"
    - script: dotnet test src/Nethermind/Nethermind.LibSolc.Test
      name: "Nethermind.LibSolc.Test.Linux"
    - script: dotnet test src/Nethermind/Nethermind.LibSolc.Test
      name: "Nethermind.LibSolc.Test.Osx"
      os: osx
    - script: dotnet test src/Nethermind/Nethermind.Mining.Test
      name: "Nethermind.Mining.Test"
    - script:
      - sudo apt-get install libsnappy-dev 
      - dotnet test src/Nethermind/Nethermind.Network.Test
      name: "Nethermind.Network.Test"
    - script: dotnet test src/Nethermind/Nethermind.Runner.Test
      name: "Nethermind.Runner.Test"
    - script: dotnet test src/Nethermind/Nethermind.Secp256k1.Test
      name: "Nethermind.Secp256k1.Test.Linux"
    - script: dotnet test src/Nethermind/Nethermind.Secp256k1.Test
      name: "Nethermind.Secp256k1.Test.Osx"
      os: osx
    - script: dotnet test src/Nethermind/Nethermind.Store.Test
      name: "Nethermind.Store.Test"