language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
addons:
  sonarcloud:
    organization: nethermindeth
    token:
      secure: "PtExebEqLhdP4eZ3nXBuiSJXNsnFMGJcZFCaUNQNs59tBnypUNC8DeTbsJ+525hANfIIImR57UYO7tYyiJLHOI+riyDx2ZN3/7E6ppeprbVtEvzmseOpOP0WukQxaI5eZ4ixABXPc8pfT6E3O0znrvp5LhAeMwCHQ3VJBoPV7LcpTzcZ0Fi5YV69MbDTGgutYuPAEpI+G7F1gU6nR+PzFxkij73NwGOYbPHJlUUH9zlJTbEUmsv8PlbXcyY+7oUPR09va66tFytZV5cTkjRSCcQACbTYtRuOyBg7Lb1InOlIDBQ/or0YOMGJlCr7nIA5SW6UThOo/psIMI02PwDHk7l7v3aHzuwHGGn2wb7jtQ/CpeKA+SIjwm9x/PYOzGHqc6t64R9mixm783GfjLXzCFro6b2IFPeHtb7lzlYtvAm8u5HERFrOZMruqneJeaTbJAhulwPkiIR0Kxjh1g9xES007fowh9vRsHUKTjR7wna74HvsbTkFiDjWNpUgG+peDKuF1rV2zlndLeMR8LmNSLJSr7YlohMryaT0sAy/IsewwZFZFD5EP0KfhCtPrVHnw1klsMWb8gd0ARtX10I46lUgxwNaPQ5qyeERT44bA6iUOcEJ4/dZAAKkQHDDCtFT3hha84eIKRf97JJpiyf324n4RRu6tSLCWei7I5pYYts="
git:
  depth: false
  submodules: false
before_script:
  - chmod -R +x scripts
notifications:
  slack:
    rooms:
      - demerzelsolutions:hzD3lmq2hbUgHuLFxjCOvk6x#team
      - demerzelsolutions:hzD3lmq2hbUgHuLFxjCOvk6x#general
after_success:
  - ./scripts/docker-publish.sh
  - sonar-scanner
after_script: 
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - stage: Build section
      script: 
      - git submodule update --init
      - dotnet build src/Nethermind/Nethermind.sln
      - dotnet build src/Nethermind/EthereumTests.sln
      name: "Build Nethermind & Ethereum"
    # - script: dotnet test src/Nethermind/Ethereum.VM.Test
    #  name: "Ethereum.VM.Test"
    - stage: Nethermind Tests section  
      script: 
      - sudo apt-get install libsnappy-dev 
      - git -c submodule."src/tests".update=none submodule update --init
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.Abi.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*" src/Nethermind/Nethermind.Blockchain.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*" src/Nethermind/Nethermind.Clique.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.Config.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.Config.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.Core.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*" src/Nethermind/Nethermind.Evm.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*" src/Nethermind/Nethermind.JsonRpc.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*" src/Nethermind/Nethermind.Mining.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*" src/Nethermind/Nethermind.Network.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.Secp256k1.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*" src/Nethermind/Nethermind.Runner.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*" src/Nethermind/Nethermind.Store.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*" src/Nethermind/Nethermind.Wallet.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.DataMarketplace.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.DataMarketplace.Consumers.Test
      name: "Nethermind Tests"
    #- script: dotnet test src/Nethermind/Nethermind.Db.Test
    #  name: "Nethermind.Db.Test.Linux"
    #- script: dotnet test src/Nethermind/Nethermind.Db.Test
    #  name: "Nethermind.Db.Test.Osx"
    #  os: osx
    #- script: dotnet test src/Nethermind/Nethermind.KeyStore.Test
    #  name: "Nethermind.KeyStore.Test"
    #- script: dotnet test src/Nethermind/Nethermind.Secp256k1.Test
    #  name: "Nethermind.Secp256k1.Test.Osx"
    #  os: osx
    # - script: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.DataMarketplace.Consumers.Test
    #  name: "Nethermind.DataMarketplace.Consumers.Test"
    #- script: dotnet test /p:CollectCNethermind.Network.TesttFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Nethermind.DatNethermind.Network.Test
    #  name: "Nethermind.DataMarketplaNethermind.Network.Test"
    #- script: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Blockchain.Test]*" src/Nethermind/Nethermind.DataMarketplace.Test
    #  name: "Nethermind.DataMarketplace.Test"
    - stage: Ethereum Tests section
      script: 
      - git submodule update --init
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.Basic.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.Blockchain.Block.Test
      - travis_wait 21 dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Ethereum.Test.Base]*" src/Nethermind/Ethereum.Blockchain.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.Difficulty.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.HexPrefix.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.KeyAddress.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.PoW.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*" src/Nethermind/Ethereum.Rlp.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.Transaction.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.Transition.Test
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*" src/Nethermind/Ethereum.Trie.Test
      name: "Ethereum Tests"